import { SearchProvider } from '@/app/providers/SearchProvider';
import QueryProvider from '@/app/providers/WithQueryProvider';
import { Navbar } from '@/widgets/Navbar/ui/Navbar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SearchProvider>
          <QueryProvider>
            <Navbar />
            {children}
          </QueryProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
